#cloud-config
# vim: syntax=yaml
# cloud-init-centos-7-ipv6.yml
# Derived from ldennison's comment in https://bugs.centos.org/view.php?id=14760 
# and from the cloud-init config in https://docs.aws.amazon.com/vpc/latest/userguide/vpc-migrate-ipv6.html#vpc-migrate-ipv6-instance-types
# The key change here is that we added /etc/sysconfig/network to the files sed considers,
# Tested on CentOS Linux release 7.6.1810 (Core)
#
# Copyright (C) 2019 by The Obscure Organization
# MIT licensed. See the LICENSE file for details.
network:
  version: 1
  config:
  - type: physical
    name: eth0
    subnets:
      - type: dhcp4
      - type: dhcp6

bootcmd:
  - "sed -i 's/^IPV6_AUTOCONF=.*$/IPV6_AUTOCONF=yes/g' /etc/sysconfig/network-scripts/ifcfg-eth0 /etc/sysconfig/network"
  - systemctl restart network
