#!/usr/bin/env bash
#
# patronus
#
# Dispel ghost logins that suck the joy out of your active terminal session
#
# Copyright (C) 2007 Richard Bullington-McGuire
# Copyright (C) 2019 The Obscure Organization
# Many thanks (and aplologies) to J.K. Rowling
#
# DISCLAIMER
#   This is a parody of J.K. Rowling's Harry Potter novels. 
#   Lawyers: please don't sue this poor house-elf who is only trying to help.
#
# Copyright (C) 2019 by The Obscure Organization
# MIT licensed. See the LICENSE file for details.
#
# Release History:
#
# 1.0 (September 6, 2007)
#  First public release
#
# 1.0.1 (May 19, 2019)
#  Relicensed under the MIT license

retval=1
MAGICAL_CREATURES=`mktemp -t patronus.XXXXXXXXXX` && {
	FLOO_NETWORK=`mktemp -t patronus.XXXXXXXXXX` && {
		
		echo "Lumos!"
		echo ""

        	ps x > $MAGICAL_CREATURES

		FLOO_EXITS=`egrep " *$$" $MAGICAL_CREATURES | \
			 awk '{print $2}'`
		awk '!/ PID/{print $2}' < $MAGICAL_CREATURES | \
			sort -u | 
			egrep -v "^\?|$FLOO_EXITS" > $FLOO_NETWORK
		DEMENTORS=`cat $FLOO_NETWORK`
		if [ -z "$DEMENTORS" ] ; then
			echo "No dementors spotted nearby."
			retval=0
		else
			DEMENTOR_KISSES=`grep -f $FLOO_NETWORK < $MAGICAL_CREATURES | \
				awk '{print $1}'`
			DEMENTOR_DESCRIPTION=`ps u $DEMENTOR_KISSES`

			cat << EOT
Traversing floo network at $FLOO_EXITS, dementors spotted at: 
$DEMENTORS

Specialis Revelio!
	
Dementors found: 
$DEMENTOR_DESCRIPTION

EXPECTO PATRONUM!
  
EOT
			kill -HUP $DEMENTOR_KISSES 2>/dev/null
			retval=$?
		fi
		rm -f $FLOO_NETWORK
	}
        rm -f $MAGICAL_CREATURES
}
exit $retval
